### PR TITLE
fix leaf.png missing for the first time;

### PR DESCRIPTION
**Pull request by ye4241**

### CODE REVIEW

**Comment by MyShiLingStar** [comment]
I do not quite understand what you are trying to fix here?

**Comment by ye4241** [comment]
At the first time of build, the ..\bin\Debug\img\Leaf.png is missing unless manual copy the downloaded temp.zip and unzip all files into Debug folder.
So, I try to add the Leaf.png into source code to let other guys build easily at the first time.

**Comment by ye4241** [comment]
Oops, I just noticed that you have updated the resources.resx with local Leaf.png file.
So, please just close this PR.

**Comment by MyShiLingStar** [comment]
Fixed I think

**Pull request closed without merging**
